# Generated by Django 2.0.7 on 2019-12-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0002_comments_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('reply', models.TextField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('basComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comments')),
            ],
            options={
                'verbose_name_plural': 'CommentReply',
            },
        ),
    ]
