# Generated by Django 2.0.7 on 2019-12-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_blog'),
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentReply',
            new_name='Replies',
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
